### ISSUE TITLE
JTI could overload the server

### ISSUE THREAD

**Issue by jaxoncreed** [matthieubosquet/ts-dpop#1]
Currently the interface calls for passing JTIs as an array, then searching through them to be sure none correspond with the DPoP JTI. (https://github.com/matthieubosquet/ts-dpop/blob/main/src/index.ts#L22)

Because a new DPoP token is generated every request, there could potentially be millions of JTIs, searching through these in `O(n)` time for every request would be cumbersome.

Instead, the function should accept an optional function that takes in a JTI and returns true if it is present. That way, the implementer can hook it up to their own custom database (`isRepeatJti?: (jti: string) => Promise<boolean>`)

**Comment by matthieubosquet** [comment]
Swapped the array for a function defaulting to an lru cache.

See: https://github.com/matthieubosquet/ts-dpop/blob/0b4ca95c8f7502d45c3f8c059785aa3512953bfd/src/lib/Verify.ts#L26-L34
