### ISSUE TITLE
JWT is manually parsed in jwt.ts

### ISSUE THREAD

**Issue by jaxoncreed** [matthieubosquet/ts-dpop#10]
Instead of manually parsing the token here https://github.com/matthieubosquet/ts-dpop/blob/main/src/jwt.ts#L5, use a library like https://www.npmjs.com/package/jsonwebtoken.

**Comment by matthieubosquet** [comment]
Won't fix, it seems like the base64url decode function that I import from panva's `jose` factors out possible issues.

See his comment on decoding secure tokens: https://github.com/panva/jose/issues/106
