### ISSUE TITLE
Jest issue: Cannot find module 'jose/jwt/verify' from 'node_modules/ts-dpop/dist/access-token.js'

### ISSUE THREAD

**Issue by RubenVerborgh** [matthieubosquet/ts-dpop#13]

**Comment by matthieubosquet** [comment]
Getting Jest to behave with Jose was a fun issue to solve involving adding a `moduleNameMapper` and `testEnvironment` to the jest config as well as adding `DOM` to the TypeScript compiler options libraries (there is a growing issue for overlapping node and browser APIs, see also: https://github.com/microsoft/TypeScript/issues/41727).

https://github.com/matthieubosquet/ts-dpop/blob/5e61dfebcff79b72ef54496496aa7420ab79f6d9/jest.config.js#L1-L20

https://github.com/matthieubosquet/ts-dpop/blob/5e61dfebcff79b72ef54496496aa7420ab79f6d9/tsconfig.json#L7

**Comment by RubenVerborgh** [comment]
👍👍 cool work, did you let the author know?

**Comment by matthieubosquet** [comment]
I did! :)

See: https://github.com/panva/jose/discussions/105#discussioncomment-210269
