### ISSUE TITLE
Interface suggestion: return an object

### ISSUE THREAD

**Issue by RubenVerborgh** [matthieubosquet/ts-dpop#15]
Currently `verify` returns a (promise to a) single string, the WebID.

I would propose to return an object `{ webId: string }` such that fields can be added easily later.
Concretely, I am thinking about details such as the issuer etc.

Also, perhaps a naming suggestion: `verifyDPoPToken`.

**Comment by matthieubosquet** [comment]
The async verify function now resolves to the access token payload which holds all relevant information.

Specifically, the webid and client_id claims.
