### ISSUE TITLE
Performance: can we make token validation faster?

### ISSUE THREAD

**Issue by RubenVerborgh** [matthieubosquet/ts-dpop#17]
At the moment, token verification easily takes over 200ms, which makes up >90% of time for many HTTP requests on the Solid Community Server.

Are there any ways to make this faster?

This is especially prohibitive when trying to perform a couple of quick `PATCH`es in succession.

**Comment by acoburn** [comment]
Here are some suggestions: cache, cache and cache

Cache the WebID lookups
Cache the issuer discovery
Cache the remote JWKS data

You will need a mechanism for evicting entries from the cache, either based on time or cache size (or both), but you definitely don't want every validation operation to require so many network lookups

**Comment by RubenVerborgh** [comment]
To have control over caching, it _might_ be an option to expose a `DPoPTokenVerifier` class, which takes constructor parameters (regarding cache duration etc.), which exposes a `verifyToken` method.

The currently exported `verify` method _could_ delegate to a default `DPoPTokenVerifier` instance then.

**Comment by matthieubosquet** [comment]
There is now a default cache for WebIDs, JWKS & JTIs.

https://github.com/matthieubosquet/ts-dpop/blob/0b4ca95c8f7502d45c3f8c059785aa3512953bfd/src/lib/Verify.ts#L26-L34

https://github.com/matthieubosquet/ts-dpop/blob/0b4ca95c8f7502d45c3f8c059785aa3512953bfd/src/lib/SolidTokenVerifier.ts#L11-L40

The current default is [lru-cache](https://www.npmjs.com/package/lru-cache). Any cache can be used as long as the respective interfaces for cached data are respected: GetIssuersFunction, GetKeySetFunction, JTICheckFunction.

https://github.com/matthieubosquet/ts-dpop/blob/0b4ca95c8f7502d45c3f8c059785aa3512953bfd/src/types/WebID.ts#L1-L3

https://github.com/matthieubosquet/ts-dpop/blob/0b4ca95c8f7502d45c3f8c059785aa3512953bfd/src/types/Issuer.ts#L1-L5

https://github.com/matthieubosquet/ts-dpop/blob/0b4ca95c8f7502d45c3f8c059785aa3512953bfd/src/types/DPoPToken.ts#L26-L28
