### ISSUE TITLE
Config fetch does not handle errors

### ISSUE THREAD

**Issue by jaxoncreed** [matthieubosquet/ts-dpop#2]
Right now, the config fetch (https://github.com/matthieubosquet/ts-dpop/blob/main/src/issuer.ts#L9-L12) blindly returns JSON. This could cause problems if the IdP errors or the JSON isn't correctly formatted.

Instead, add a check to be sure the server returned `200` and that `jwks_uri` is present and a valid uri.

This will also prevent you from needing to cast the returned value to `any` which is generally an anti-pattern (https://github.com/matthieubosquet/ts-dpop/blob/main/src/issuer.ts#L9-L12)

The same goes for the jwk request (https://github.com/matthieubosquet/ts-dpop/blob/main/src/issuer.ts#L20-L23). Don't return JSON, return a type.

I like the pattern you had going in `type-guard`.  Use that here too.

**Comment by matthieubosquet** [comment]
Issuer config now checks the response status and that the jwks_uri is present and can be parsed as a URL.

https://github.com/matthieubosquet/ts-dpop/blob/5e61dfebcff79b72ef54496496aa7420ab79f6d9/src/lib/Issuer.ts#L19-L55
