### ISSUE TITLE
Make certain function names more descriptive

### ISSUE THREAD

**Issue by jaxoncreed** [matthieubosquet/ts-dpop#3]
webId.ts 
- `oidcIssuer` -> `getOidcIssuerUriFromWebId`

jwt.ts
 - `webID` -> `getWebIdFromJwt`

issuer.ts
 - `issuerConfigUrl` -> `getIssuerConfigUrl`
 - `config` -> `getOpenIdConfiguration`
 - `jwks_uri` -> `getJwksUri`
 - `jwks` -> `getJwks`

dpop.ts
 - `verify` -> `verifyDpopToken`

access-token.ts
 - `verify` -> `verifyAccessToken`

**Comment by matthieubosquet** [comment]
The place where I see the `get`/`set` prefixes convention used is in Java class mutator and accessor methods. I don't think it is relevant for functions.

I find brevity in context more legible and elegant.

For example:
- `src/lib/DPoP.ts` exposes a verify function that can be easily understood as the function that verifies DPoPs
- `src/lib/AccessToken.ts` exposes a verify function that can be easily understood as the function that verifies Access tokens

Exposing a `verifyDPoPToken` function in a `DPoP.ts` to me is redundant.

In turn, when both are required, you can:
```javascript
import { verify as verifyAccessToken } from "./AccessToken";
import { verify as verifyDPoPToken } from "./DPoP";
```

I admit it is to a great extent a matter of taste, but I would always aim for brevity and eliminating what I see as redundant information in a given context.
