### ISSUE TITLE
Oidc Issuer might be an empty array

### ISSUE THREAD

**Issue by jaxoncreed** [matthieubosquet/ts-dpop#4]
The OIDC Issuer function could possibly return an empty array if there is no `solid:oidcIssuer` present in the WebId (https://github.com/matthieubosquet/ts-dpop/blob/main/src/webid.ts#L19-L24)

It is blindly assumed that the array has a first element here: https://github.com/matthieubosquet/ts-dpop/blob/main/src/access-token.ts#L28

This should be adjusted to error elegantly if the array is empty.

**Comment by matthieubosquet** [comment]
Fixed.

See: https://github.com/matthieubosquet/ts-dpop/blob/0b4ca95c8f7502d45c3f8c059785aa3512953bfd/src/lib/AccessToken.ts#L88-L91
