### ISSUE TITLE
Types should be interfaces

### ISSUE THREAD

**Issue by jaxoncreed** [matthieubosquet/ts-dpop#6]
In this file (https://github.com/matthieubosquet/ts-dpop/blob/main/src/type.ts) any time you have a type that follows `type SomeType = { key: value }`, it should actually be `interface SomeType { key: value }`.

That should also be picked up by the ESlinter if the suggestion here is implemented: https://github.com/matthieubosquet/ts-dpop/issues/5

**Comment by matthieubosquet** [comment]
Done.
