### ISSUE TITLE
Issuer and WebId tests depend on an outside server

### ISSUE THREAD

**Issue by jaxoncreed** [matthieubosquet/ts-dpop#9]
Currently, the issuer tests make requests out to a live server at `https://broker.demo-ess.inrupt.com` (https://github.com/matthieubosquet/ts-dpop/blob/main/test/issuer.test.ts#L4). Tests should never depend on a resource outside the test environment. If `https://broker.demo-ess.inrupt.com` were ever to go down, these tests would fail.

The same goes for https://github.com/matthieubosquet/ts-dpop/blob/main/test/webid.test.ts#L4

**Comment by matthieubosquet** [comment]
All tests rewritten and fixed.
